server.port: 9003
spring:
  application:
    name: kuke-board-view-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/article_view
#    url: jdbc:mysql://192.168.219.106:3306/article_view
    url: jdbc:mysql://49.175.22.52:3306/article_view
    username: root
    password: 1541
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092